trigger:
  branches:
   include:     
     - main
  paths:
    include:
    - dockeragent

stages:
  - stage: CI
    displayName: Build-Push de la Imagen
    jobs:
    - job: Docker
      displayName: Build and push Image
      pool: 
        vmImage: ubuntu-latest
      steps:
        - task: Docker@2
          displayName: Build image
          inputs:
            command: build
            containerRegistry: 'Jmhh-Production-Acr'
            repository: 'linux-agents'
            Dockerfile: 'dockeragent/Dockerfile'
            buildContext: 'dockeragent/'
            tags: |
              $(Build.BuildId)
              latest
              
        - task: Docker@2
          displayName: Push image
          inputs:
            containerRegistry: 'Jmhh-Production-Acr'
            repository: 'linux-agents'
            command: push
            tags: |
              $(Build.BuildId)
              latest  
